### ISSUE TITLE
source code 2.1

### ISSUE THREAD

**Issue by irweazel** [kartoone/mybiketraffic#2]
Hi
   great work on the project, would you be able to update the source code for the latest release so i can side load onto the 1030plus until they sort out the SDK?
thanks
Chris

**Comment by kartoone** [comment]
No problem, I just pushed the latest code to github. You may want to compile it yourself or you can probably grab the .PRG file in the bin folder and use it as is for side-loading. Either way should work great. Let me know if you run into any issues.  Brian

**Comment by irweazel** [comment]
brilliant thanks, i'll give the lazy option a go first :) quite interesting to see the actual code as i've not played around with anything other than python before

**Comment by irweazel** [comment]
looks like the lack of SDK support means i can't add the extra fields from the mobile app...at least i can enjoy a bit of geeking on the post ride data
ignore that i managed to sort it from the simulator settings and export :)

**Comment by kartoone** [comment]
Supposedly the store version works now as it shows up on the list of compatible devices. I don’t have a 1030 plus to test it on … can you completely uninstall it and then try reinstalling the store version?

**Comment by irweazel** [comment]
all done, everything seems fine on the activity data screens...i'll do a ride later and let you know :)

**Comment by irweazel** [comment]
all the fields show up but there seem to be some issues with the vehicle count...i saw it not count or count extra a few times. 30mile ride 188 cars feels like quite a lot.
Edge 1030 plus - Varia 515

**Comment by kartoone** [comment]
It struggles counting when there are a bunch of cars. It tends to undercount in that situation. As far as extra cars go, it’s possible that you are seeing it increment at unexpected times. The exact moment the count increases is when a car disappears off the radar after it has crossed a threshold of 30meters behind you. So it will have some false positives if the car turns off early. The count won’t increment until the car disappears, though (either from passing you or turning early). I’m going to add the threshold distance as a setting for the next version of the app. Some people would prefer to set it at 0 to reduce false positives, but I feel like that misses too many cars in busy situations.

**Comment by cagnulein** [comment]
@irweazel  since @kartoone is away, do you have a simple FIT file that I can use for reference for #6 
Thanks!
